# Generated by Django 3.2.5 on 2022-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=None, default='placeholder.png', null=True, upload_to='images'),
        ),
    ]
